module.exports = {
    name: "8ball",
    aliases: [],
    category: "3.1. 🎲 | Entertainment",
    description: "Ask the magic 8 ball a question",
    usage: "[quetsion]",
    permissions: "SEND_MESSAGES",
    clientPerms: "SEND_MESSAGES",
    guildOnly: false,
    creatorOnly: false,
    run: async (client, msg, args) => {
        if(args.length < 3) return msg.channel.send(`${client.Emojis.x} Try asking a proper question next time..`);
        let As = ["I have no clue", "I don't think so", "I think so", "Try and see", "Definitely NOT", "Definitely", "Proabably not", "Probably", "No", "Yes", "I didn't catch that. Say again?", "Always", "Never", "Of course", "One hundered percent", "Try again next time", "Maybe", `It is certain.`,
            `It is decidedly so.`,
            `Without a doubt.`,
            "Yes - definitely.",
            "You may rely on it.",
            "As I see it, yes.",
            "Most likely.",
            "Outlook good.",
            "Yes.",
            "Signs point to yes.",
            "Reply hazy, try again.",
            "Ask again later.",
            "Better not tell you now.",
            "Cannot predict now.",
            "Concentrate and ask again.",
            "Don't count on it.",
            "My reply is no.",
            "My sources say no.",
            "Outlook not so good.",
            "Very doubtful.",
            "Maybe",
            "That is sure as hell.",
            "Fire.",
            "Indeed.",
            "Try to be usefull.",
            "Watch the birds.",
            "Gold.",
            "Answer is uncertain.",
            "You are the master of your life",
            "Maybe no.",
            "We can not be never sure.",
            "As you wish.",
            "Eat less, move more.",
            "Better ask yourself.",
            "Just do it.",
            "Sorry, but this is really stupid question.",
            "Try to be usefull.",
            "Water.",
            "We can not be never sure.",
            "You already know the Answer.",
            "Very bad idea.",
            "Never.",
            "Maybe yes.",
            "Mabye no."
        ];
        let A = As[Math.floor(Math.random() * As.length)];
        msg.channel.send(A);
    }
};